FROM node:lts-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm ci

# Copier le reste du code
COPY . .

# Définir l'environnement
ENV NODE_ENV=development

# Exposer le port du serveur
EXPOSE 5000

# Démarrer l'application
CMD ["npm", "run", "dev"]
